FROM alpine:3.22

ARG NEXUS_BACKUP_VERSION=dev
ARG NEXUS_BACKUP_REVISION=unknown
ARG REST_SERVER_VERSION=0.14.0
ARG REST_SERVER_SHA256=4c9c95bc079a0334e81fad379b19dc5c3353c71c2c88d652cafce2081c2b1c66

LABEL org.opencontainers.image.title="Nexus Backup Repository" \
      org.opencontainers.image.description="TLS-authenticated Restic REST repository endpoint for Nexus Backup workstations" \
      org.opencontainers.image.source="https://github.com/swamp2k/nexus_backup" \
      org.opencontainers.image.version="$NEXUS_BACKUP_VERSION" \
      org.opencontainers.image.revision="$NEXUS_BACKUP_REVISION" \
      org.opencontainers.image.vendor.rest-server.version="$REST_SERVER_VERSION"

RUN apk add --no-cache apache2-utils ca-certificates curl openssl tini \
    && mkdir -p /tmp/rest-server \
    && curl -fL --retry 3 --retry-delay 2 \
      "https://github.com/restic/rest-server/releases/download/v${REST_SERVER_VERSION}/rest-server_${REST_SERVER_VERSION}_linux_amd64.tar.gz" \
      -o /tmp/rest-server.tar.gz \
    && echo "${REST_SERVER_SHA256}  /tmp/rest-server.tar.gz" | sha256sum -c - \
    && tar -xzf /tmp/rest-server.tar.gz -C /tmp/rest-server \
    && REST_SERVER_BIN="$(find /tmp/rest-server -maxdepth 2 -type f -name 'rest-server*' -print -quit)" \
    && test -n "$REST_SERVER_BIN" \
    && install -m 0755 "$REST_SERVER_BIN" /usr/local/bin/rest-server \
    && rm -rf /tmp/rest-server /tmp/rest-server.tar.gz

COPY repository/docker-entrypoint.sh /usr/local/bin/nexus-repository-entrypoint
COPY repository/client.sh /usr/local/bin/nexus-repository-client
RUN chmod 0755 /usr/local/bin/nexus-repository-entrypoint /usr/local/bin/nexus-repository-client \
    && mkdir -p /config /public /data

ENV NEXUS_BACKUP_VERSION=$NEXUS_BACKUP_VERSION \
    NEXUS_BACKUP_REVISION=$NEXUS_BACKUP_REVISION \
    NEXUS_BACKUP_REPOSITORY_PORT=8000 \
    NEXUS_BACKUP_REPOSITORY_PUBLIC_PORT=8001

EXPOSE 8000 8001
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/nexus-repository-entrypoint"]
