const content=document.querySelector("#content"),nav=document.querySelector('[data-view="repositories"]'),title=document.querySelector("#page-title"),eyebrow=document.querySelector("#page-eyebrow"),refreshButton=document.querySelector("#refresh-button"),newButton=document.querySelector("#new-job-button"),toastStack=document.querySelector("#toast-stack");
let repositories=[],users=[],busy=false;
nav?.addEventListener("click",()=>{location.hash="repositories";activate()});window.addEventListener("hashchange",activate);new MutationObserver(()=>{if(active()&&!content.querySelector("#repositories-view"))queueMicrotask(render)}).observe(content,{childList:true});activate();
newButton?.addEventListener("click",event=>{if(!active())return;event.preventDefault();event.stopImmediatePropagation();newRepository()});
function active(){return(location.hash.replace(/^#/ ,"")||"overview")==="repositories"}
function activate(){if(!active())return;document.querySelectorAll("[data-view]").forEach(item=>item.classList.toggle("active",item===nav));if(title)title.textContent="Repositories";if(eyebrow)eyebrow.textContent="Flat-file storage";if(newButton){newButton.hidden=false;newButton.textContent="New repository"} ;void refresh()}
async function refresh(){if(busy)return;busy=true;try{const [repoResult,userResult]=await Promise.all([api("/v1/local/repositories"),api("/v1/local/receiver-users")]);repositories=repoResult.repositories??[];users=userResult.users??[];render()}catch(error){toast("Repositories failed",error.message,true)}finally{busy=false}}
function render(){if(!active())return;content.innerHTML=`<div id="repositories-view"><div class="transfer-hero"><div><p class="eyebrow">Ordinary folders under /backup</p><h2>Repositories</h2><p>Each Repository is a named storage folder. Files remain readable and browsable without Nexus or a special recovery tool.</p></div><button class="button primary" data-new-repository>New repository</button></div><div class="entity-grid section-gap">${repositories.map(repositoryCard).join("")||empty("No repositories yet","Create a repository to start storing backups.")}</div><section class="card card-pad section-gap"><div class="card-header"><div><p class="eyebrow">Receiver access</p><h2>Transfer users</h2><p>Restricted SFTP, FTP and WebDAV users for cameras, software and other upload clients.</p></div><button class="button ghost" data-new-user>Create user</button></div><div class="table-wrap mt-16">${users.length?`<table><thead><tr><th>Username</th><th>Root</th><th>Kind</th><th>Status</th><th></th></tr></thead><tbody>${users.map(userRow).join("")}</tbody></table>`:empty("No receiver users","Workstation enrollment creates one automatically.")}</div></section><div class="transfer-note mt-16"><strong>Receiver ports:</strong> SFTP 2222 · FTP 2121 · WebDAV through the Nexus HTTP service. FTP passive ports are documented in the appliance configuration.</div></div>`;bind()}
function repositoryCard(repo){return`<article class="entity-card"><div class="entity-meta"><strong>${esc(repo.name)}</strong><code>/backup/${esc(repo.relativePath)}</code><p>Created ${esc(date(repo.createdAt))}</p></div><div class="entity-icon">▣</div></article>`}
function userRow(user){return`<tr><td><span class="cell-primary">${esc(user.username)}</span><span class="cell-sub">${esc(user.kind)}</span></td><td><code>/backup/${esc(repositories.find(repo=>repo.id===user.repositoryId)?.relativePath||"")}${user.relativeSubpath?`/${esc(user.relativeSubpath)}`:""}</code></td><td>${esc(user.repositoryName||"—")}</td><td>${badge(user.enabled?"Enabled":"Disabled",user.enabled?"success":"warn")}</td><td><button class="button ghost compact" data-toggle-user="${attr(user.id)}">${user.enabled?"Disable":"Enable"}</button><button class="button ghost compact" data-reset-user="${attr(user.id)}">Reset password</button></td></tr>`}
function bind(){content.querySelector("[data-new-repository]")?.addEventListener("click",newRepository);content.querySelector("[data-new-user]")?.addEventListener("click",newUser);content.querySelectorAll("[data-toggle-user]").forEach(button=>button.addEventListener("click",async()=>{const user=users.find(item=>item.id===button.dataset.toggleUser);if(!user)return;try{await api(`/v1/local/receiver-users/${encodeURIComponent(user.id)}`,{method:"PATCH",body:{enabled:!user.enabled}});await refresh()}catch(error){toast("Receiver update failed",error.message,true)}}));content.querySelectorAll("[data-reset-user]").forEach(button=>button.addEventListener("click",async()=>{try{const result=await api(`/v1/local/receiver-users/${encodeURIComponent(button.dataset.resetUser)}/reset-password`,{method:"POST",body:{}});showSecret("New receiver password",result.password)}catch(error){toast("Password reset failed",error.message,true)}}))}
function newRepository(){showForm("New repository",`<label><span>Name</span><input name="name" required maxlength="255" placeholder="Family PCs"></label><label><span>Location <small>optional</small></span><input name="relativePath" placeholder="Defaults to /backup/&lt;name&gt;"></label>`,async form=>{const result=await api("/v1/local/repositories",{method:"POST",body:{name:form.name.value,relativePath:form.relativePath.value||undefined}});toast("Repository created",result.repository.name);await refresh()})}
function newUser(){if(!repositories.length){toast("Create a repository first","Receiver users need a restricted root.",true);return}showForm("Create receiver user",`<label><span>Username</span><input name="username" required maxlength="64" placeholder="camera"></label><label><span>Repository</span><select name="repositoryId">${repositories.map(repo=>`<option value="${attr(repo.id)}">${esc(repo.name)}</option>`).join("")}</select></label><label><span>Subfolder <small>optional</small></span><input name="relativeSubpath" placeholder="Camera Uploads"></label><p class="muted-2">A random 32-byte password will be generated and shown once.</p>`,async form=>{const result=await api("/v1/local/receiver-users",{method:"POST",body:{username:form.username.value,repositoryId:form.repositoryId.value,relativeSubpath:form.relativeSubpath.value||undefined}});closeForm();showSecret("Receiver password",`${result.password}\n\nSFTP: sftp://${result.user.username}@${location.hostname}:2222\nFTP: ftp://${result.user.username}@${location.hostname}:2121\nWebDAV: http://${location.host}/dav/${result.user.username}`);await refresh()})}
function showForm(heading,fields,submit){const modal=document.createElement("div");modal.className="modal-backdrop";modal.id="repository-modal";modal.innerHTML=`<section class="modal"><div class="modal-header"><h2>${esc(heading)}</h2><button class="icon-button" data-close>×</button></div><form>${fields}<div class="modal-actions"><button type="button" class="button ghost" data-close>Cancel</button><button type="submit" class="button primary">Save</button></div></form></section>`;document.body.append(modal);modal.querySelectorAll("[data-close]").forEach(item=>item.addEventListener("click",closeForm));modal.querySelector("form").addEventListener("submit",event=>{event.preventDefault();const form=event.currentTarget;submit(form).then(closeForm).catch(error=>toast("Save failed",error.message,true))})}
function closeForm(){document.querySelector("#repository-modal")?.remove()}
function showSecret(title,value){showForm(title,`<p class="muted-2">This value is shown once. Store it in the client that will connect to Nexus.</p><pre class="payload">${esc(value)}</pre>`,async()=>{}) ;document.querySelector("#repository-modal form .modal-actions")?.remove()}
function empty(head,body){return`<div class="empty"><strong>${esc(head)}</strong>${esc(body)}</div>`}function badge(text,tone=""){return`<span class="badge ${tone}">${esc(text)}</span>`}function date(value){try{return new Date(value).toLocaleDateString()}catch{return"—"}}function esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}function attr(value){return esc(value)}
async function api(path,{method="GET",body}={}){const response=await fetch(path,{method,headers:{accept:"application/json",...(body===undefined?{}:{"content-type":"application/json"})},body:body===undefined?undefined:JSON.stringify(body),cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`${response.status} ${response.statusText}`);return data}
